/*
EXEC SP_LookupHobby_GetAll



*/
TRUNCATE TABLE LookupHobby
GO

-- Indoor
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','3D printing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Acrobatics')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Acting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Amateur radio')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Animation')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Aquascaping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Astronomy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Baking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Baton twirling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Beatboxing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Blogging')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Building')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Board/tabletop games')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Book discussion clubs')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Book restoration')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Brazilian jiu-jitsu')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Breadmaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cabaret')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Calligraphy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Candle making')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Car fixing & building')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Card games')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cheesemaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Clothesmaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Coffee roasting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Coloring')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Computer programming')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Confectionery')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cooking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cosplaying')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Couponing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Craft')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Creative writing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Crocheting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cross-stitch')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Crossword puzzles')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cryptography')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cue sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Dance')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Digital arts')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Distro Hopping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Djing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Do it yourself')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Drama')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Drawing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Drink mixing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Electronics')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Embroidery')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Experimenting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fantasy sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fashion')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fashion design')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Flower arranging')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Foreign language learning')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Furniture building')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Gaming (tabletop games and role-playing games)')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Genealogy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Gingerbread house making')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Glassblowing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Graphic design')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Gunsmithing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Herp keeping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Home improvement')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Homebrewing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Hula hooping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Hydroponics')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Jewelry making')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Jigsaw puzzles')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Journaling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Juggling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Karaoke')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Karate')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Kendama')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Knife making')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Knitting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Knot tying')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Kombucha brewing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Lace making')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Lapidary')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Leather crafting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Lego building')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Lock picking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Listening to music')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Listening to podcasts')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Machining')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Macrame')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Magic')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Makeup')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Metalworking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Model building')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Model engineering')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Nail art')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Needlepoint')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Origami')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Painting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Pet adoption & fostering')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Philately')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Photography')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Practical jokes')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Pressed flower craft')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Playing musical instruments')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Poi')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Pottery')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Puzzles')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Quilling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Quizzes')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Rapping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Refinishing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Robot combat')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Rubik''s Cube')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Scrapbooking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Sculpting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Sewing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Shoemaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Singing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Sketching')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Soapmaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Social media')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Stand-up comedy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Stamp collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Table tennis')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Taxidermy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Thrifting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Video editing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Video game developing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Video gaming')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Watching movies')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Watching television')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Weaving')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Weight training')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Welding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Whittling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Wikipedia editing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Winemaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Wood carving')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Woodworking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Worldbuilding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Writing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Word searches')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Yo-yoing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Yoga')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Action figure')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Antiquing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Art collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Book collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cartophily (card collecting)')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Coin collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Comic book collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Deltiology (postcard collecting)')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Die-cast toy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Dolls')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Element collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Ephemera collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fusilately (phonecard collecting)')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Knife collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Lotology (lottery ticket collecting)')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Movie and movie memorabilia collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Perfume')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Phillumeny')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Rail transport modelling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Record collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Rock tumbling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Scutelliphily')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Shoes')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Sports memorabilia')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Stuffed toy collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Tea bag collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Ticket collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Toys')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Video game collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Vintage cars')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Vintage clothing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Vinyl Records')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Animal fancy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Axe throwing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Badminton')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Beauty pageants')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Billiards')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Bowling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Boxing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Bridge')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Cheerleading')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Chess')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Color guard')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Curling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Dancing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Darts')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Debate')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Eating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Esports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fencing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Go')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Gymnastics')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Ice hockey')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Ice skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Judo')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Jujitsu')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Kabaddi')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Laser tag')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Longboarding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Mahjong')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Marbles')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Martial arts')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Poker')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Shogi')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Slot car racing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Speedcubing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Sport stacking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Table football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Volleyball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Weightlifting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Wrestling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Fishkeeping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Learning')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Meditation')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Microscopy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Reading')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Shortwave listening')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Audiophile')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Indoor','Videophilia')

-- Outdoor
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Air sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Astronomy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Backpacking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','BASE jumping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Baseball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Basketball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Beekeeping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Blacksmithing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','BMX')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Board sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Bodybuilding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Bonsai')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Butterfly watching')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Camping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Canoeing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Canyoning')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Caving')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Composting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Dowsing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Driving ')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Flag football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Flower growing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Flying')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Flying disc')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Foraging')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Freestyle football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Gardening')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Geocaching')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Ghost hunting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Gold prospecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Graffiti')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Herbalism')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','High-power rocketry')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Hiking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Hobby horsing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Hooping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Hunting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Inline skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Jogging')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Kayaking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Kite flying')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Kitesurfing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','LARPing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Letterboxing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Martial arts')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Motor sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Mountain biking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Mountaineering')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Mushroom hunting/mycology')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Netball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Nordic skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Orienteering')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Paintball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Parkour')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Podcast hosting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Polo')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Powerlifting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rafting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rappelling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Road biking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rock climbing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Roller skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rugby')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Running')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Sailing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Sand art')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Scouting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Scuba diving')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Shooting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Shopping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Skiing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Skimboarding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Skydiving')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Slacklining')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Snowboarding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Soccer')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Stone skipping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Sun bathing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Survivalism')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Taekwondo')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Tai chi')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Topiary')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Travel')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Urban exploration')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Vacation')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Vegetable farming')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Vehicle restoration')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Walking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Water sports')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Antiquities')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Auto audiophilia')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Flower collecting and pressing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Fossil hunting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Insect collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Magnet fishing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Metal detecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Mineral collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rock balancing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Sea glass collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Seashell collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Stone collecting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Airsoft')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','American football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Archery')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Association football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Australian rules football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Auto racing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Beach volleyball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Breakdancing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Climbing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Cricket')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Cycling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Disc golf')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Dog sport')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Equestrianism')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Exhibition drill')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Field hockey')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Figure skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Fishing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Footbag')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Golfing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Handball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Horseback riding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Jukskei')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Kart racing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Knife throwing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Lacrosse')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Longboarding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Marching band')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Model aircraft')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Racquetball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Radio-controlled car racing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Roller derby')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Rugby league football')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Sculling or rowing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Shooting sport')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Skateboarding')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Softball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Speed skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Squash')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Surfing')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Swimming')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Table tennis')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Tennis')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Tennis polo')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Tether car')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Tour skating')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Trapshooting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Triathlon')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Ultimate frisbee')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Volleyball')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Water polo')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Aircraft spotting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Amateur astronomy')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Birdwatching')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Bus spotting')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Geocaching')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Gongoozling')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Herping')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Hiking/backpacking')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Meteorology')
INSERT INTO LookupHobby (LocationType, Description) VALUES ('Outdoor','Photography')
